repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff lint
        entry: ruff check --fix organelle_svg
        language: system
        types: [python]
        pass_filenames: false
      - id: ruff-format
        name: ruff format
        entry: ruff format organelle_svg
        language: system
        types: [python]
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: mypy --python-executable=.venv/bin/python3 organelle_svg
        language: system
        types: [python]
        pass_filenames: false
