from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from datetime import timezone
from typing import TYPE_CHECKING

from .config import SOURCE
from .og_colors import get_colors_for_genome


if TYPE_CHECKING:
    from typing import Callable
    from Bio.SeqRecord import SeqRecord
    from .svg import TEXT_TYPE
    from .og_colors import PatternKeys, ColourTuple

GC_HIST_BACKGROUND = "rgb(217,217,217)"
HISTOGRAM_COLORS = {"depth": "rgba(250,0,0,.6)", "coverage": "rgba(0,0,255,.6)"}
STRAND_COLORS = {1: "rgb(239,59,44)", -1: "rgb(66,146,198)"}
# background color for SFF in normal plot
BG_COLOR_SFF = "#aaaaff"


def colorer(genome: str, *, by: PatternKeys = "pattern") -> Callable[[str], str]:
    colours = get_colors_for_genome(genome)
    C = [(d[by], d["color"]) for d in colours if d["drawflag"]]

    def color(gene: str) -> str:
        c: ColourTuple = 0, 0, 0

        for m, color in C:
            if m.match(gene):
                c = color
                break
        a = "" if len(c) == 3 else "a"
        return f"rgb{a}({','.join(str(s) for s in c)})"

    return color


@dataclass
class RenderTips:
    show_legend: bool = True
    show_center_text: bool = True


class GenomeInfo:
    inline: bool = False
    whoami: str | None = "Chloë"
    TZ = datetime.now(timezone.utc).astimezone().tzinfo

    def genome(self, rec: SeqRecord, default: str = "chloroplast") -> str:
        if "source" not in rec.annotations:
            return default
        txt = str(rec.annotations["source"])

        m = SOURCE.match(str(txt))
        return m.group(1) if m else default

    def center_text_list(
        self,
        rec: SeqRecord,
        default: str = "chloroplast",
    ) -> tuple[TEXT_TYPE, str]:
        # turn & into &amp; but
        # only 5 predefined entities are known for
        # XML escape only uses these 5

        if "source" not in rec.annotations:
            txt = ""
        else:
            txt = str(rec.annotations["source"])

        m = SOURCE.match(txt)
        if m:
            genome, txt = m.group(1, 2)
        else:
            genome = default  # for colors in legend
        txt = txt.strip()
        if "(" in txt:
            i = txt.index("(")
            tt = [txt[:i].strip(), txt[i:].strip()]
        else:
            tt = [txt]

        text = [genome, *tt, f"{len(rec.seq if rec.seq else ' '):,} bp"]
        return text, genome

    def legend_text(self, typ: str) -> list[tuple[str, ColourTuple | None]]:
        C = get_colors_for_genome(typ)
        # name and color as r,g,b as a string
        lines: list[tuple[str, ColourTuple | None]] = [
            (r["fullname"], r["color"]) for r in C if r["drawflag"]
        ]
        if self.whoami:
            tme = datetime.now(tz=self.TZ)
            lines.append(
                (f"generated by {self.whoami} on {tme.isoformat()}", None),
            )
        return lines
